source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
workspace 'SchedulableObjectDemo'

abstract_target 'SchedulableObjectDemo' do
    project 'SchedulableObjectDemo.xcodeproj'
    target 'Dev'
    pod 'CocoaLumberjack'
    pod 'ComponentKit'
    pod 'GCNetworkReachability'
    pod 'POSRx', :git => 'https://github.com/pavelosipov/POSRx.git'
    pod 'POSJSONParsing', :git => 'https://github.com/pavelosipov/POSJSONParsing.git'
    pod 'RDHCollectionViewGridLayout'
end

abstract_target 'SchedulableObjectDemoTests' do
    project 'SchedulableObjectDemo.xcodeproj'
    target 'Tests'
    pod 'CocoaLumberjack'
    pod 'POSRx', :git => 'https://github.com/pavelosipov/POSRx.git'
    pod 'POSJSONParsing', :git => 'https://github.com/pavelosipov/POSJSONParsing.git'
    pod 'POSAllocationTracker'
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SDKROOT'] = "iphoneos"
            config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
        end
    end
end
